CREATE TABLE `4*40` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ADDACT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `AERODYNAMICS` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `AESTHETICS` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `AimatFame` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `AIRSHOOT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `APTO-TECH` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `AZIZFLY` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `AIRRUSH` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BALOONPYRAMID` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BARTERPUZZLES` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Battle-O-Web` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BEERSHEER` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Bidtowin` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BindenKnoop` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BLASTANDHUNT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BlindWalk` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BLINDCODING` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `BlindDrawing` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BLINDFOLLOWER` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `BLINDHUNT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BOLLYWOODMANIA` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BOTTOMSUP` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BOUNCETHECOIN` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BRAINHUNT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BRAINQUEST` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BRAINTEASER` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BUGS4EVER` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `BUSINESSMASTER` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Camouflage` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `CARSOCCER` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `CoinGlassyJunction` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `CardStaker` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `CATCHTHECLIPS` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `CHAUSAR` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `CARPOOL` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `CleanBowled` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `COMPETEANDCONQUER` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ConnectingCodes` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `COWBOY` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `CREATIVECODE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `CRYPTOMANIA` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Cubecasting` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `CUPBATTLE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `DARE2DARE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `DUMBCHARADES` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `DASTAAR` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `DESIGNYOURWEB` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `DevilFollows` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ELEKTRA` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ENGINEERSEYE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `EXQUIZME` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `FAISLAONTHESPOT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `FAMEFORMINUTE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `FETCHEMFINDTHEVIEW` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `FIZIKA` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `FASTANDFURIOUS` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `FUTSAL` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `GIRLZONE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `GlassPyramid` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `GENERALQUIZWITHPRAGYAN` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `GYROASEMBLY` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Housie` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `HitTheRoad` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Humanfooseball` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Hunkthejunk` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Inquizate` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ITQuiz` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `KEYBOARDWAR` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `LASTSHOT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `LINEFOLLOWER` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `LogoDesign` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `LOGOMANIA` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `LORDOFCODE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `LUCKBYCHANCE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `LUCKYELECTRICIANS` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `LUDOWIZ` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `MAD-AD` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `MinesField` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `MINIMILITIA` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `MOCKPLACEMENTDRIVE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `MOCKSSB` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `MODELLING&MODULATION` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `MRMISSTECH` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `MAZESOLVER` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `PAPERPRESENTATION` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `PNEUMATICCIRCUIT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `POPART` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `PICTOHUNT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `PopsicleSpindle` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Pourfruitlebeire` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `QueryMaster` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `QUIZOHOLICS` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `REACHTHESKY` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `RIDDLES` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `RIDEONCODE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ROADIES-BeaRebel` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ROBOCON` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ROBOSUSPENSION` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ROBORACE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ROBOWAR` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Rangoon` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Seismicstraws` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `SENSEIT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `SHOOTNANSWER` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Prizeinashot` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `SPARTANSIX` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `SPINTHEWHEEL` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `StringofBeads` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TECHSCRATCH` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TECHTALKS` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TECHNOPICTIONARY` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TECHNICALTREASUREHUNT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TECHNICALWRITINGS` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TECHNICIAN.Ωhm` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Technoquiz` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TIMEREFLEX` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TECHNOVANZA` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TECHNOVISUALQUIZTECHNICAL` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TECHNOZARRE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `THUNDER-TheGamingZone` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TRYYOURLUCK` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TurbanTying` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `TWISTOFFATE` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `VIRTOTEM` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Whimsicalbraids` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `WIN-LIGHT` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `WIZARDTHETESLA` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `Zumba` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;